version: '3'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"